### ISSUE TITLE
.EXE

### ISSUE THREAD

**Issue by Mika-IO** [AntonioABLima/Contador-De-Piscadas#1]
Seria super interessante ter um instalável do projeto.
Seria magnifico o pisca ter instalado isso na máquina dele e executar na livekkkkkk.

Ainda n rodei o projeto mas quais seriam os desafios disso? Sou programador Python e se vc me permitir @AntonioABLima posso trabalhar nisso e criar um PR pro seu repo. A idéia é bem vinda?

Aguardo a  resposta e tenha um bom dia minerin... 👍🙏

**Comment by AntonioABLima** [comment]
Fala ae Mikaio, a ideia é super bem vinda, eu e mais 3 colegas estamos nos dedicando para criar um contador para a live deve, muita coisa ainda não foi feita só discutimos 2 possibilidades, a primeira foi ideia minha que é pegar o contador jogar só o número mesmo (aquele que fica na esquerda) com um fundo verde para a uma câmera virtual que depois é só colocar no OBS, a segunda é parecida com o que este cara fez : https://www.youtube.com/watch?v=ZMJpKGmxdB0. Fica o convite para trabalhar com a gente (e aparecer em um possível shorts/tiktok)! Caso não queira, sinal verde para sua ideia, únicos desafios são: perguntar pro orochinho qual resolução e fps ele grava e temos que saber o tamanho do olho do homi.
[https://www.bing.com/th?id=OVP.IrpO1ud_NxtE_vL2rV7MLwHgFo&pid=Api]<https://www.youtube.com/watch?v=ZMJpKGmxdB0>
Create your own OBS Plugin with JS, CSS and HTML<https://www.youtube.com/watch?v=ZMJpKGmxdB0>
This tutorial works for both OBS Studio and XSplit. This is a quick way to add new features to your live steams. For XSplit, you'll wanna drag the index.html onto the scene as there is no way to specify a local file otherwise. Original idea: https://www.youtube.com/watch?v=_bwfAPXlFu8 Free plugins on Github: https://github.com/kgiszewski/Live ...
www.youtube.com

________________________________
De: Mikaio ***@***.***>
Enviado: quinta-feira, 14 de setembro de 2023 11:24
Para: AntonioABLima/Contador-De-Piscadas ***@***.***>
Cc: Antônio Alexandre Borges Lima ***@***.***>; Mention ***@***.***>
Assunto: [AntonioABLima/Contador-De-Piscadas] .EXE (Issue #1)


Seria super interessante ter um instalável do projeto.
Seria magnifico o pisca ter instalado isso na máquina dele e executar na livekkkkkk.

Ainda n rodei o projeto mas quais seriam os desafios disso? Sou programador Python e se vc me permitir @AntonioABLima<https://github.com/AntonioABLima> posso trabalhar nisso e criar um PR pro seu repo. A idéia é bem vinda?

Aguardo a resposta e tenha um bom dia minerin... 👍🙏

**Comment by AntonioABLima** [comment]
E bom dia para você também!
________________________________
De: Antônio Alexandre Borges Lima ***@***.***>
Enviado: quinta-feira, 14 de setembro de 2023 17:55
Para: AntonioABLima/Contador-De-Piscadas ***@***.***>
Assunto: RE: [AntonioABLima/Contador-De-Piscadas] .EXE (Issue #1)

Fala ae Mikaio, a ideia é super bem vinda, eu e mais 3 colegas estamos nos dedicando para criar um contador para a live deve, muita coisa ainda não foi feita só discutimos 2 possibilidades, a primeira foi ideia minha que é pegar o contador jogar só o número mesmo (aquele que fica na esquerda) com um fundo verde para a uma câmera virtual que depois é só colocar no OBS, a segunda é parecida com o que este cara fez : https://www.youtube.com/watch?v=ZMJpKGmxdB0. Fica o convite para trabalhar com a gente (e aparecer em um possível shorts/tiktok)! Caso não queira, sinal verde para sua ideia, únicos desafios são: perguntar pro orochinho qual resolução e fps ele grava e temos que saber o tamanho do olho do homi.
[https://www.bing.com/th?id=OVP.IrpO1ud_NxtE_vL2rV7MLwHgFo&pid=Api]<https://www.youtube.com/watch?v=ZMJpKGmxdB0>
Create your own OBS Plugin with JS, CSS and HTML<https://www.youtube.com/watch?v=ZMJpKGmxdB0>
This tutorial works for both OBS Studio and XSplit. This is a quick way to add new features to your live steams. For XSplit, you'll wanna drag the index.html onto the scene as there is no way to specify a local file otherwise. Original idea: https://www.youtube.com/watch?v=_bwfAPXlFu8 Free plugins on Github: https://github.com/kgiszewski/Live ...
www.youtube.com

________________________________
De: Mikaio ***@***.***>
Enviado: quinta-feira, 14 de setembro de 2023 11:24
Para: AntonioABLima/Contador-De-Piscadas ***@***.***>
Cc: Antônio Alexandre Borges Lima ***@***.***>; Mention ***@***.***>
Assunto: [AntonioABLima/Contador-De-Piscadas] .EXE (Issue #1)


Seria super interessante ter um instalável do projeto.
Seria magnifico o pisca ter instalado isso na máquina dele e executar na livekkkkkk.

Ainda n rodei o projeto mas quais seriam os desafios disso? Sou programador Python e se vc me permitir @AntonioABLima<https://github.com/AntonioABLima> posso trabalhar nisso e criar um PR pro seu repo. A idéia é bem vinda?

Aguardo a resposta e tenha um bom dia minerin... 👍🙏
